/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author palsa
 */
public class AccountMgnJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountMgnJPanel
     */
    private JPanel pnlCard;
    private AccountDirectory accDir;

    AccountMgnJPanel(JPanel pnlCard, AccountDirectory accDir) {
        initComponents();
        this.pnlCard=pnlCard;
        this.accDir=accDir;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrAcc = new javax.swing.JButton();
        btnMgnAcc = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnCrAcc.setText("Create Account");
        btnCrAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrAccActionPerformed(evt);
            }
        });

        btnMgnAcc.setText("Manage Account");
        btnMgnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMgnAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMgnAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(btnCrAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(705, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnCrAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnMgnAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrAccActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel createAcc=new CreateAccountJPanel(pnlCard,accDir);
        pnlCard.add("CreateAccountJPanel", createAcc);
        CardLayout cardLayout=(CardLayout) pnlCard.getLayout();
        cardLayout.next(pnlCard);
        
    }//GEN-LAST:event_btnCrAccActionPerformed

    private void btnMgnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMgnAccActionPerformed
        // TODO add your handling code here:
        ManageJPanel mngAcc=new ManageJPanel(pnlCard,accDir);
        pnlCard.add("ManageJPanel", mngAcc);
        CardLayout cardLayout=(CardLayout) pnlCard.getLayout();
        cardLayout.next(pnlCard);
        
    }//GEN-LAST:event_btnMgnAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrAcc;
    private javax.swing.JButton btnMgnAcc;
    // End of variables declaration//GEN-END:variables
}
