/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.Account;
import business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author palsa
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPanel
     */
    private JPanel pnlCard;
    private AccountDirectory accDir;
    private boolean exist=false;
    
    CreateAccountJPanel(JPanel pnlCard, AccountDirectory accDir) {
        initComponents();
        this.accDir=accDir;
        this.pnlCard=pnlCard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbRouNum = new javax.swing.JLabel();
        lbAccNum = new javax.swing.JLabel();
        lbBankName = new javax.swing.JLabel();
        lbBal = new javax.swing.JLabel();
        txtRouNum = new javax.swing.JTextField();
        txtAccNum = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtBal = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Account");

        lbRouNum.setText("Routing Number:");

        lbAccNum.setText("Account Number:");

        lbBankName.setText("Bank Name:");

        lbBal.setText("Balance:");

        txtRouNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRouNumActionPerformed(evt);
            }
        });

        txtBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalActionPerformed(evt);
            }
        });

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(lbBal)
                    .addComponent(lbBankName)
                    .addComponent(lbAccNum)
                    .addComponent(lbRouNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRouNum)
                        .addComponent(txtAccNum)
                        .addComponent(txtBankName)
                        .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRouNum)
                    .addComponent(txtRouNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAccNum)
                    .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBankName)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBal)
                    .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRouNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRouNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRouNumActionPerformed

    private void txtBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        exist=false;
        if(txtRouNum.getText().equals("") || txtAccNum.getText().equals("") || txtBankName.getText().equals("") || txtBal.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all the fields to proceed with account creation");
        }
        
        else if (!txtRouNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Routing number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (!txtAccNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Account number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (!txtBal.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Please enter only numeric values for Balance!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
                            
        else
        {
        String routingNumber=txtRouNum.getText();
        String accountNumber=txtAccNum.getText();
        int balance=Integer.parseInt(txtBal.getText());
        String bankName=txtBankName.getText();
        for (Account acc: accDir.getAccountList())
        {
            if(acc.getRoutingNumber().equals(txtRouNum.getText())||acc.getAccountNumber().equals(txtAccNum.getText()))
            {
                JOptionPane.showMessageDialog(this, "Account already exist", "Warning", JOptionPane.WARNING_MESSAGE);
                exist = true;
                break;
            }
        }
        
        if(exist==false)
        {
        Account account= accDir.addAccount();
        account.setRoutingNumber(routingNumber);
        account.setAccountNumber(accountNumber);
        account.setBankName(bankName);
        account.setBalance(balance);
        
        JOptionPane.showMessageDialog(this, "Account created successfully!");
        }
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        pnlCard.remove(this);
        CardLayout layout= (CardLayout) pnlCard.getLayout();
        layout.previous(pnlCard);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAccNum;
    private javax.swing.JLabel lbBal;
    private javax.swing.JLabel lbBankName;
    private javax.swing.JLabel lbRouNum;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRouNum;
    // End of variables declaration//GEN-END:variables
}
