/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import business.Account;
import business.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author palsa
 */

public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
   
    private JPanel pnlCard;
    private Account account;
    private AccountDirectory accDir;
    ViewAccountJPanel(JPanel pnlCard, Account account, AccountDirectory accDir) {
     initComponents();
     this.pnlCard=pnlCard;
     this.account=account;
     this.accDir=accDir;
     populateAccountDtls();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbRouNum = new javax.swing.JLabel();
        lbAccNum = new javax.swing.JLabel();
        lbBankName = new javax.swing.JLabel();
        txtRouNum = new javax.swing.JTextField();
        txtAccNum = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Account");

        lbRouNum.setText("Routing Number:");

        lbAccNum.setText("Account Number:");

        lbBankName.setText("Bank Name:");

        txtRouNum.setEditable(false);
        txtRouNum.setEnabled(false);
        txtRouNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRouNumActionPerformed(evt);
            }
        });

        txtAccNum.setEditable(false);
        txtAccNum.setEnabled(false);

        txtBankName.setEditable(false);
        txtBankName.setEnabled(false);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbBankName)
                            .addComponent(lbAccNum)
                            .addComponent(lbRouNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRouNum, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtAccNum)
                            .addComponent(txtBankName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(37, 37, 37)
                        .addComponent(btnUpdate)
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRouNum)
                    .addComponent(txtRouNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAccNum)
                    .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBankName)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        pnlCard.remove(this);
        CardLayout layout= (CardLayout) pnlCard.getLayout();
        layout.previous(pnlCard);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtRouNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRouNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRouNumActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        if(txtRouNum.getText().equals("") || txtAccNum.getText().equals("") || txtBankName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all the fields to proceed with account creation", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (!txtRouNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Routing number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (!txtAccNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Account number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else
        {
        txtAccNum.setEditable(true);
        txtBankName.setEditable(true);
        txtRouNum.setEditable(true);
        txtAccNum.setEnabled(true);
        txtBankName.setEnabled(true);
        txtRouNum.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(txtRouNum.getText().equals("") || txtAccNum.getText().equals("") || txtBankName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter all the fields to proceed with account creation", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        
        else if (!txtAccNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Account number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (!txtRouNum.getText().matches("^[0-9]+$"))
        {
            JOptionPane.showMessageDialog(this, "Routing number doesn't accept special characters or alphabets. Please enter only numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
        else
        { 
            account.setAccountNumber(txtAccNum.getText());
            account.setBankName(txtBankName.getText());
            account.setRoutingNumber(txtRouNum.getText());                
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Account saved successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAccNum;
    private javax.swing.JLabel lbBankName;
    private javax.swing.JLabel lbRouNum;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRouNum;
    // End of variables declaration//GEN-END:variables

    private void populateAccountDtls() {
        txtAccNum.setText(account.getAccountNumber());
        txtBankName.setText(account.getBankName());
        txtRouNum.setText(account.getRoutingNumber());
    }
}
